### ISSUE TITLE
Create the CLI for Expresso TS

### ISSUE THREAD

**Issue by Daniel-Boll** [expressots/expressots-cli#1]
# <h1 align="center">Steps required</h1>

## CLI Specification

First we will need to create a CLI specification, that means, every use case for the CLI utility, i.e.:

```bash
expressots-cli --help
xts --help
```
More than one name perhaps.

---

Creating a new project?

```bash
xts new project
xts import project --url=https://github.com/expressots/expressots-templates/tree/-/main/example-crud
```

----

Creating a new so called `resource` that would be the whole package os `useCases`, `repository`, `entity`.

```bash
xts new resource
   -> name
   -> generate tests?
```

---

Singular creations of resources, for instance a new useCase

```bash
xts new use-case book/loan # a use case that was not default generated
```

## Tools

The CLI probably should be created using TypeScript for the sake of the environment of the affected users (expresso is a JavaScript framework, therefore we suppose that they have a JavaScript environment set, although languages like Go and Rust are better to create a CLI). <--- Discussion needed.

## Packaging

Probably in a separate package called `expresso-ts-cli`, `expressots-cli`, `@expressots/cli`, `@expresso-ts/cli` or any other permutations.

**Comment by rsaz** [comment]
![image](https://user-images.githubusercontent.com/4088378/216862030-5dab0539-8885-4ccd-a685-41a779ce3148.png)

Please refer to the Jira ticket to update your tasks in the comments section.
https://brdev.atlassian.net/browse/XTS-52

**Comment by rsaz** [comment]
Generate and schema done, we need to keep polishing the solution. For now, everything is stable and the base solution is delivered. 
https://www.npmjs.com/package/@expressots/cli
