### ISSUE TITLE
Wrong import in the module when generating a new controller.

### ISSUE THREAD

**Issue by eryk-vieira** [expressots/expressots-cli#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When generating a new controller with:

`expressots g controller <path>`

It creates the controller normally but it adds a broken import to the module
![image](https://github.com/expressots/expressots-cli/assets/59400564/8e4b0a98-f973-47d1-9266-857b8e1bf397)
![image](https://github.com/expressots/expressots-cli/assets/59400564/330b27be-ede4-420c-80c8-b344873f2a1c)

### Steps to reproduce

1. `expressots g controller <path>`
2. checkout the added import on the respective module the controller was added to.

### Expected behavior

When generating a new controller it should be added a **"./"** preventing this bug to happen.

### Package version

1.3.1

### Node.js version

18.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by rsaz** [comment]
Hi @eryk-vieira thank you for the PR #13 

Problem resolved in the `v1.3.2`

Now you can use your command `expressots g controller user/something/` and being able to get the appropriate generated scaffold without the extra trailing comma as well in the controller module. 

- Linux Test: Pass
- Mac Test: Pass
- Win Test: Pass

![image](https://github.com/expressots/expressots-cli/assets/4088378/de53040f-55c3-43fb-9951-dec8dfa7af80)

**Comment by eryk-vieira** [comment]
@rsaz Sounds Good!
Thanks for approving the PR and for the interest of solving the case as soon as possible.

**Comment by rsaz** [comment]
That's the goal, we are trying to be fast as we can. And thanks for your contribution, keep contributing. :)
