### ISSUE TITLE
Scaffold resources from CLI on v2.0.0 is using wrong dependencies

### ISSUE THREAD

**Issue by rsaz** [expressots/expressots-cli#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

With the release of v2.0.0 few dependencies were removed from the project such as inversify utils, chalk and winston. Also, the the express server definitions were moved to the adapter-express repo causing the templates to be updated in favor of this change

### Steps to reproduce

expressots new 
expressots generate

Both commands are not scaffolding the correct templates

### Expected behavior

Generating the templates with the new dependencies

### Package version

2.0.0

### Which project template was used?

- [X] opinionated
- [X] non-opinionated

### Node.js version

18.11.0

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [x] Linux

### Which Package Managers have you tested?

- [x] NPM
- [x] YARN
- [x] PNPM

**Comment by Daniel-Boll** [comment]
@rsaz, the base template from the Opinionated format contains a rough implementation of an InMemoryDB provider, right? As it's an out-of-the-box provider right now, the example may be updated to only sort of import the provider.

**Comment by rsaz** [comment]
Issue fixed in the PR #20
