### ISSUE TITLE
Add Bun support in the CLI

### ISSUE THREAD

**Issue by juliano-soares** [expressots/expressots-cli#22]
## Proposal:
I propose adding support for the Bun CLI (bunx) in ExpressoTS CLI. Bunx is a tool that offers improved speed and efficiency when running locally installed packages. By adding bunx support, we can enhance the developer experience for ExpressoTS users and make package execution faster.

## Benefits:

Faster Execution: Bunx is faster than npx for locally installed packages. This enhancement will lead to significantly faster package execution times for ExpressoTS users.

Efficient Package Management: Bunx checks for locally installed packages first and falls back to installing from npm if needed. This ensures that users have access to the latest package versions.

Improved Developer Experience: ExpressoTS users will benefit from a smoother and more efficient CLI experience, making it easier to work with the framework.

## Implementation Details:
To add bunx support to the ExpressoTS CLI, we will need to:

Modify the CLI to recognize and use the bunx command.
Ensure that bunx respects and executes packages as expected.
Test the integration thoroughly to ensure compatibility and performance improvements.

**Comment by rsaz** [comment]
Closed in PR #23
